app:
  name: 'go-example'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'error'
  rollbar_env: 'go-example'

postgres:
  pool_max: 2
  url: 'postgres://postgres:postgres@localhost:5432/hh'
