app:
  name: 'go-mall-api'
  version: '1.0.0'

http:
  port: '8080'
  version: '1'

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

datasource:
  pg:
    url: 'postgres://postgres:postgres@localhost:5432/hh'
    pool_max: 20

prometheus:
  gateway: 'http://localhost:9091/'
